### ISSUE TITLE
load err

### ISSUE THREAD

**Issue by tpkeeper** [eq-lab/ledger-substrate-app-demo#1]
mac os 13.3.1 
python 3.11.3
node v16.13.0
ledger nano s plus(firmware 1.1.0)

```
app/installer_s2.sh load
```

```
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/tpkeeper/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 253, in <module>
    loader.createApp(code_length, args.apiLevel, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/Users/tpkeeper/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ledgerblue/hexLoader.py", line 346, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/Users/tpkeeper/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ledgerblue/hexLoader.py", line 189, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpkeeper/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6512 (Unknown reason)
```

**Comment by tpkeeper** [comment]
After testing, it seems like the [unified sdk](https://github.com/LedgerHQ/ledger-secure-sdk) is required to support the latest firmware.

**Comment by Overseven** [comment]
@tpkeeper  Can you try to use these commands?
```bash
pip install ledgerblue
/bin/bash ./installer_s.sh load
```
And install commands from here:
https://github.com/eq-lab/app-substrate-common/blob/master/docs/build.md

I have only Nano S ledger and can't test it on Nano S Plus version

**Comment by tpkeeper** [comment]
sure, but got the same `6512` err

this issue is the same to this [https://github.com/Zondax/ledger-polkadot/issues/187](https://github.com/Zondax/ledger-polkadot/issues/187)

I test the ledger-polkdadot(version >= v21.9390) with [unified sdk](https://github.com/LedgerHQ/ledger-secure-sdk) and is ok
but the ledger-polkdadot(version = v20.9370 ) with [the old sdk](https://github.com/LedgerHQ/nanosplus-secure-sdk)  got the same `6512` error

so, i believe the reason is that the sdk and the firmware not match

**Comment by tpkeeper** [comment]
And sadly, I didn't find a way to downgrade the firmware version

**Comment by Overseven** [comment]
Thanks for clarification.
I will find the way to fix it if our treasury proposal for general Substrate app will be approved. 
Currently, you may to use a Ledger Nano S for running this demo or use a Ledger emulator: https://github.com/LedgerHQ/speculos
